# Generated by Django 2.2.9 on 2020-11-17 14:52

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audiofile',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='bookimg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('A', 'Arts & Music'), ('B', 'Biographies'), ('BA', 'Business'), ('C', 'Comics'), ('CM', 'Computers & tech'), ('E', 'Edu & Reference'), ('H', 'History'), ('HR', 'Horror'), ('M', 'Mysterise'), ('R', 'Religion'), ('RM', 'Romance')], default=343, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='readpdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 14, 52, 40, 492725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
