# Generated by Django 2.2.9 on 2020-11-17 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20201117_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 14, 56, 59, 305275, tzinfo=utc)),
        ),
    ]
