# Generated by Django 2.2.9 on 2020-11-17 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20201117_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 15, 4, 47, 394611, tzinfo=utc)),
        ),
    ]
