# Generated by Django 2.2.9 on 2020-11-17 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_auto_20201117_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 15, 6, 5, 983313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Arts & Music', 'Arts & Music'), ('Biographies', 'Biographies'), ('Business', 'Business'), ('Comics', 'Comics'), ('Computers & tech', 'Computers & tech'), ('Edu & Reference', 'Edu & Reference'), ('History', 'History'), ('Horror', 'Horror'), ('Mysterise', 'Mysterise'), ('Religion', 'Religion'), ('Romance', 'Romance')], max_length=220),
        ),
    ]
